# Generated by Django 5.2.4 on 2025-08-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_store_manager_alter_school_name_alter_store_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='manager',
        ),
    ]
