# Generated by Django 5.2.4 on 2025-07-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_managersettings_purchase_amount_purchase_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
